[[manager.prepend_keymap]]
on   = [ 'g', 'd' ]
exec = 'cd ~/dev'
desc = 'Go to the dev directory'

[[manager.prepend_keymap]]
on   = [ 'g', 'D' ]
exec = 'cd ~/Downloads'
desc = 'Go to the downloads directory'

[[manager.prepend_keymap]]
on   = [ 'g', '<Enter>' ]
exec = 'cd ~/Desktop'
desc = 'Go to the Desktop directory'

[[manager.prepend_keymap]]
on   = [ 'g', 'v' ]
exec = 'cd ~/.config/nvim'
desc = 'Go to the neovim config directory'

[[manager.prepend_keymap]]
on   = [ "$" ]
exec = 'shell "$SHELL" --block --confirm'
desc = 'Open shell here'

[[manager.prepend_keymap]]
on   = [ '<A-a>' ]
exec = 'select_all --state=true'
desc = 'Select all files'

[[manager.prepend_keymap]]
on   = [ '<A-r>' ]
exec = 'select_all --state=none'
desc = 'Inverse selection of all files'

# Bookmarks--------------------------------------------------------------------

[[manager.prepend_keymap]]
on = [ 'm' ]
exec = 'plugin bookmarks --args=save'
desc = 'Save current position as a bookmark'

[[manager.prepend_keymap]]
on = [ "'" ]
exec = 'plugin bookmarks --args=jump'
desc = 'Jump to a bookmark'

[[manager.prepend_keymap]]
on = [ 'b', 'd' ]
exec = 'plugin bookmarks --args=delete'
desc = 'Delete a bookmark'

[[manager.prepend_keymap]]
on = [ 'b', 'D' ]
exec = 'plugin bookmarks --args=delete_all'
desc = 'Delete all bookmarks'

# Relative motions ------------------------------------------------------------

[[manager.prepend_keymap]]
on = [ '1' ]
exec = 'plugin relative-motions --args=1'
desc = 'Move in relative steps'

[[manager.prepend_keymap]]
on = [ '2' ]
exec = 'plugin relative-motions --args=2'
desc = 'Move in relative steps'

[[manager.prepend_keymap]]
on = [ '3' ]
exec = 'plugin relative-motions --args=3'
desc = 'Move in relative steps'

[[manager.prepend_keymap]]
on = [ '4' ]
exec = 'plugin relative-motions --args=4'
desc = 'Move in relative steps'

[[manager.prepend_keymap]]
on = [ '5' ]
exec = 'plugin relative-motions --args=5'
desc = 'Move in relative steps'

[[manager.prepend_keymap]]
on = [ '6' ]
exec = 'plugin relative-motions --args=6'
desc = 'Move in relative steps'

[[manager.prepend_keymap]]
on = [ '7' ]
exec = 'plugin relative-motions --args=7'
desc = 'Move in relative steps'

[[manager.prepend_keymap]]
on = [ '8' ]
exec = 'plugin relative-motions --args=8'
desc = 'Move in relative steps'

[[manager.prepend_keymap]]
on = [ '9' ]
exec = 'plugin relative-motions --args=9'
desc = 'Move in relative steps'
