[manager]
sort_by = "natural"
sort_dir_first = true
linemode = "size"
show_hidden = true

[plugin]
prepend_previewers = [
  { name = "*.md", exec = "glow" },
  { mime = "text/csv", exec = "miller" },
]
