[manager]
sort_by = "natural"
sort_dir_first = true
linemode = "size"
show_hidden = true
scrolloff = 5

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
  { mime = "text/csv", run = "miller" },
]
