[manager]
sort_by = "natural"
sort_dir_first = true
linemode = "size"
show_hidden = true
scrolloff = 5

[opener]
extract = [
    { run = 'for archive in %s; do unar -q -r "$archive"; done', desc = "Extract here (unar)", for = "unix", block = true },
]

[plugin]
prepend_previewers = [
    { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
    { mime = "text/csv", run = "miller" },
]
prepend_fetchers = [
    { url = "*", run = "git", group = "git" },
    { url = "*/", run = "git", group = "git" },
]
